linters:

  BorderZero:
    enabled: true
    convention: none

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: false

  HexLength:
    enabled: false

  HexNotation:
    enabled: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 4

  LeadingZero:
    enabled: false

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: true

  StringQuotes:
    enabled: true
    style: double_quotes

  TransitionAll:
    enabled: true
